languages = [ "en", "es", "fr" ]

# ENGLISH ########################################################
[en]
language = "English"
help = '''
help - List with all commands available
/***************************************\
* - status Get the server status        *
*    List the version and creation date *
*    Show total players                 *
*    Show total spectators              *
*    Server life (in seconds)           * 
*                                       *
* - help Show all commands and usage    *
*                                       *
* - lang [--help] <name>                *
*    Change server language             *
*    The output will change             *
*    Commands will never change         *
*                                       *
* - clear Clear the console scree       *
*                                       *
* - exit Exit the server                *
\***************************************/'''
welcome_to_server = '''

Welcome to the Zappy Server!

░██╗░░░░░░░██╗███████╗██╗░░░░░░█████╗░░█████╗░███╗░░░███╗███████╗
░██║░░██╗░░██║██╔════╝██║░░░░░██╔══██╗██╔══██╗████╗░████║██╔════╝
░╚██╗████╗██╔╝█████╗░░██║░░░░░██║░░╚═╝██║░░██║██╔████╔██║█████╗░░
░░████╔═████║░██╔══╝░░██║░░░░░██║░░██╗██║░░██║██║╚██╔╝██║██╔══╝░░
░░╚██╔╝░╚██╔╝░███████╗███████╗╚█████╔╝╚█████╔╝██║░╚═╝░██║███████╗
░░░╚═╝░░░╚═╝░░╚══════╝╚══════╝░╚════╝░░╚════╝░╚═╝░░░░░╚═╝╚══════╝
'''
total_players = "Total Players"
total_spectators = "Total Spectators"
server_life = "Server's Life"
language_help = '''
lang [--help] <name>

Change the language of the server
Replace <name> by any language you want to use
Ex.
  $> lang es
  $> lang --help
'''

# SPANISH ########################################################
[es]
language = "Espanol"
help = "Ayuda - Lista de todos los comandos disponibles"
welcome_to_server = '''
Bienvenido al Servidor Zappy!
 ____  _                           _     _       _ 
| __ )(_) ___ _ ____   _____ _ __ (_) __| | ___ | |
|  _ \| |/ _ \ '_ \ \ / / _ \ '_ \| |/ _` |/ _ \| |
| |_) | |  __/ | | \ V /  __/ | | | | (_| | (_) |_|
|____/|_|\___|_| |_|\_/ \___|_| |_|_|\__,_|\___/(_)
'''
total_players = "Total de Jugadores"
total_spectators = "Total de Espectadores"
server_life = "Vida del Servidor"
language_help = '''
lang [--help] <nombre>

Cambiar el lenguage del servidor
Remplaza <nombre> por lenguage que quieres utilizar
Ej.
  $> lang es
  $> lang --help
'''

# FRENCH ########################################################
[fr]
language = "French"
help = "Aide - List tout les commandes disponibles"
welcome_to_server = '''
Bienvenue aux Zappy Server!
 _     _                                      
| |   (_)                                     
| |__  _  ___ _ ____   _____ _ __  _   _  ___ 
| '_ \| |/ _ \ '_ \ \ / / _ \ '_ \| | | |/ _ \
| |_) | |  __/ | | \ V /  __/ | | | |_| |  __/
|_.__/|_|\___|_| |_|\_/ \___|_| |_|\__,_|\___|
'''
total_players = "Total des Joueurs"
total_spectators = "Total de Spectateurs"
server_life = "Vie du Server"
language_help = '''
lang [--help] <nom>

Change la langue du server
Reemplis le <nom> pour quel que langue gue tu a soahtez
Ex.
  $> lang es
  $> lang --help
'''